#This GH Actions is the final one. This will be trigger by a master push

name: GitHub Actions Demo
run-name: Master job.
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    name: Maven build test and Docker Push
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
      - name: Terraform installation
        uses: hashicorp/setup-terraform@v2

      # TIP: The buildx must be before the others docker actions.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Testing docker push action
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: juancastro96/personal-repo:example-${{ github.sha }}